apiVersion: v1
kind: Service
metadata:
  name: ulipvahanapi-service
  namespace: ulipsystem
spec:
  selector:
    app: ulipvahanapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: internalotrulipapi-service
  namespace: ulipsystem
spec:
  selector:
    app: internalotrulipapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ulipfastagapi-service
  namespace: ulipsystem
spec:
  selector:
    app: ulipfastagapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ulipintermodalapi-service
  namespace: ulipsystem
spec:
  selector:
    app: ulipintermodalapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
